// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: add.proto

package com.tanmoy.ContactFindService.proto;

public final class Add {
  private Add() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface FindRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:FindRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 id = 1;</code>
     */
    int getId();
  }
  /**
   * Protobuf type {@code FindRequest}
   */
  public  static final class FindRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:FindRequest)
      FindRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use FindRequest.newBuilder() to construct.
    private FindRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private FindRequest() {
      id_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private FindRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              id_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.tanmoy.ContactFindService.proto.Add.internal_static_FindRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.tanmoy.ContactFindService.proto.Add.internal_static_FindRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.tanmoy.ContactFindService.proto.Add.FindRequest.class, com.tanmoy.ContactFindService.proto.Add.FindRequest.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <code>int32 id = 1;</code>
     */
    public int getId() {
      return id_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0) {
        output.writeInt32(1, id_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.tanmoy.ContactFindService.proto.Add.FindRequest)) {
        return super.equals(obj);
      }
      com.tanmoy.ContactFindService.proto.Add.FindRequest other = (com.tanmoy.ContactFindService.proto.Add.FindRequest) obj;

      boolean result = true;
      result = result && (getId()
          == other.getId());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.tanmoy.ContactFindService.proto.Add.FindRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.tanmoy.ContactFindService.proto.Add.FindRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.tanmoy.ContactFindService.proto.Add.FindRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.tanmoy.ContactFindService.proto.Add.FindRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.tanmoy.ContactFindService.proto.Add.FindRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.tanmoy.ContactFindService.proto.Add.FindRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.tanmoy.ContactFindService.proto.Add.FindRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.tanmoy.ContactFindService.proto.Add.FindRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.tanmoy.ContactFindService.proto.Add.FindRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.tanmoy.ContactFindService.proto.Add.FindRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.tanmoy.ContactFindService.proto.Add.FindRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.tanmoy.ContactFindService.proto.Add.FindRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.tanmoy.ContactFindService.proto.Add.FindRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code FindRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:FindRequest)
        com.tanmoy.ContactFindService.proto.Add.FindRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.tanmoy.ContactFindService.proto.Add.internal_static_FindRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.tanmoy.ContactFindService.proto.Add.internal_static_FindRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.tanmoy.ContactFindService.proto.Add.FindRequest.class, com.tanmoy.ContactFindService.proto.Add.FindRequest.Builder.class);
      }

      // Construct using com.tanmoy.ContactFindService.proto.Add.FindRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        id_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.tanmoy.ContactFindService.proto.Add.internal_static_FindRequest_descriptor;
      }

      @java.lang.Override
      public com.tanmoy.ContactFindService.proto.Add.FindRequest getDefaultInstanceForType() {
        return com.tanmoy.ContactFindService.proto.Add.FindRequest.getDefaultInstance();
      }

      @java.lang.Override
      public com.tanmoy.ContactFindService.proto.Add.FindRequest build() {
        com.tanmoy.ContactFindService.proto.Add.FindRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.tanmoy.ContactFindService.proto.Add.FindRequest buildPartial() {
        com.tanmoy.ContactFindService.proto.Add.FindRequest result = new com.tanmoy.ContactFindService.proto.Add.FindRequest(this);
        result.id_ = id_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.tanmoy.ContactFindService.proto.Add.FindRequest) {
          return mergeFrom((com.tanmoy.ContactFindService.proto.Add.FindRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.tanmoy.ContactFindService.proto.Add.FindRequest other) {
        if (other == com.tanmoy.ContactFindService.proto.Add.FindRequest.getDefaultInstance()) return this;
        if (other.getId() != 0) {
          setId(other.getId());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.tanmoy.ContactFindService.proto.Add.FindRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.tanmoy.ContactFindService.proto.Add.FindRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int id_ ;
      /**
       * <code>int32 id = 1;</code>
       */
      public int getId() {
        return id_;
      }
      /**
       * <code>int32 id = 1;</code>
       */
      public Builder setId(int value) {
        
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 id = 1;</code>
       */
      public Builder clearId() {
        
        id_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:FindRequest)
    }

    // @@protoc_insertion_point(class_scope:FindRequest)
    private static final com.tanmoy.ContactFindService.proto.Add.FindRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.tanmoy.ContactFindService.proto.Add.FindRequest();
    }

    public static com.tanmoy.ContactFindService.proto.Add.FindRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<FindRequest>
        PARSER = new com.google.protobuf.AbstractParser<FindRequest>() {
      @java.lang.Override
      public FindRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new FindRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<FindRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<FindRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.tanmoy.ContactFindService.proto.Add.FindRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ApiResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ApiResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string responseMessage = 1;</code>
     */
    java.lang.String getResponseMessage();
    /**
     * <code>string responseMessage = 1;</code>
     */
    com.google.protobuf.ByteString
        getResponseMessageBytes();

    /**
     * <code>int32 responseCode = 2;</code>
     */
    int getResponseCode();

    /**
     * <code>.Contact contact = 3;</code>
     */
    boolean hasContact();
    /**
     * <code>.Contact contact = 3;</code>
     */
    com.tanmoy.ContactFindService.proto.ContactOuterClass.Contact getContact();
    /**
     * <code>.Contact contact = 3;</code>
     */
    com.tanmoy.ContactFindService.proto.ContactOuterClass.ContactOrBuilder getContactOrBuilder();
  }
  /**
   * Protobuf type {@code ApiResponse}
   */
  public  static final class ApiResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ApiResponse)
      ApiResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ApiResponse.newBuilder() to construct.
    private ApiResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ApiResponse() {
      responseMessage_ = "";
      responseCode_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ApiResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              responseMessage_ = s;
              break;
            }
            case 16: {

              responseCode_ = input.readInt32();
              break;
            }
            case 26: {
              com.tanmoy.ContactFindService.proto.ContactOuterClass.Contact.Builder subBuilder = null;
              if (contact_ != null) {
                subBuilder = contact_.toBuilder();
              }
              contact_ = input.readMessage(com.tanmoy.ContactFindService.proto.ContactOuterClass.Contact.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(contact_);
                contact_ = subBuilder.buildPartial();
              }

              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.tanmoy.ContactFindService.proto.Add.internal_static_ApiResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.tanmoy.ContactFindService.proto.Add.internal_static_ApiResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.tanmoy.ContactFindService.proto.Add.ApiResponse.class, com.tanmoy.ContactFindService.proto.Add.ApiResponse.Builder.class);
    }

    public static final int RESPONSEMESSAGE_FIELD_NUMBER = 1;
    private volatile java.lang.Object responseMessage_;
    /**
     * <code>string responseMessage = 1;</code>
     */
    public java.lang.String getResponseMessage() {
      java.lang.Object ref = responseMessage_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        responseMessage_ = s;
        return s;
      }
    }
    /**
     * <code>string responseMessage = 1;</code>
     */
    public com.google.protobuf.ByteString
        getResponseMessageBytes() {
      java.lang.Object ref = responseMessage_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        responseMessage_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int RESPONSECODE_FIELD_NUMBER = 2;
    private int responseCode_;
    /**
     * <code>int32 responseCode = 2;</code>
     */
    public int getResponseCode() {
      return responseCode_;
    }

    public static final int CONTACT_FIELD_NUMBER = 3;
    private com.tanmoy.ContactFindService.proto.ContactOuterClass.Contact contact_;
    /**
     * <code>.Contact contact = 3;</code>
     */
    public boolean hasContact() {
      return contact_ != null;
    }
    /**
     * <code>.Contact contact = 3;</code>
     */
    public com.tanmoy.ContactFindService.proto.ContactOuterClass.Contact getContact() {
      return contact_ == null ? com.tanmoy.ContactFindService.proto.ContactOuterClass.Contact.getDefaultInstance() : contact_;
    }
    /**
     * <code>.Contact contact = 3;</code>
     */
    public com.tanmoy.ContactFindService.proto.ContactOuterClass.ContactOrBuilder getContactOrBuilder() {
      return getContact();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getResponseMessageBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, responseMessage_);
      }
      if (responseCode_ != 0) {
        output.writeInt32(2, responseCode_);
      }
      if (contact_ != null) {
        output.writeMessage(3, getContact());
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getResponseMessageBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, responseMessage_);
      }
      if (responseCode_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, responseCode_);
      }
      if (contact_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, getContact());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.tanmoy.ContactFindService.proto.Add.ApiResponse)) {
        return super.equals(obj);
      }
      com.tanmoy.ContactFindService.proto.Add.ApiResponse other = (com.tanmoy.ContactFindService.proto.Add.ApiResponse) obj;

      boolean result = true;
      result = result && getResponseMessage()
          .equals(other.getResponseMessage());
      result = result && (getResponseCode()
          == other.getResponseCode());
      result = result && (hasContact() == other.hasContact());
      if (hasContact()) {
        result = result && getContact()
            .equals(other.getContact());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + RESPONSEMESSAGE_FIELD_NUMBER;
      hash = (53 * hash) + getResponseMessage().hashCode();
      hash = (37 * hash) + RESPONSECODE_FIELD_NUMBER;
      hash = (53 * hash) + getResponseCode();
      if (hasContact()) {
        hash = (37 * hash) + CONTACT_FIELD_NUMBER;
        hash = (53 * hash) + getContact().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.tanmoy.ContactFindService.proto.Add.ApiResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.tanmoy.ContactFindService.proto.Add.ApiResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.tanmoy.ContactFindService.proto.Add.ApiResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.tanmoy.ContactFindService.proto.Add.ApiResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.tanmoy.ContactFindService.proto.Add.ApiResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.tanmoy.ContactFindService.proto.Add.ApiResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.tanmoy.ContactFindService.proto.Add.ApiResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.tanmoy.ContactFindService.proto.Add.ApiResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.tanmoy.ContactFindService.proto.Add.ApiResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.tanmoy.ContactFindService.proto.Add.ApiResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.tanmoy.ContactFindService.proto.Add.ApiResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.tanmoy.ContactFindService.proto.Add.ApiResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.tanmoy.ContactFindService.proto.Add.ApiResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ApiResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ApiResponse)
        com.tanmoy.ContactFindService.proto.Add.ApiResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.tanmoy.ContactFindService.proto.Add.internal_static_ApiResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.tanmoy.ContactFindService.proto.Add.internal_static_ApiResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.tanmoy.ContactFindService.proto.Add.ApiResponse.class, com.tanmoy.ContactFindService.proto.Add.ApiResponse.Builder.class);
      }

      // Construct using com.tanmoy.ContactFindService.proto.Add.ApiResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        responseMessage_ = "";

        responseCode_ = 0;

        if (contactBuilder_ == null) {
          contact_ = null;
        } else {
          contact_ = null;
          contactBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.tanmoy.ContactFindService.proto.Add.internal_static_ApiResponse_descriptor;
      }

      @java.lang.Override
      public com.tanmoy.ContactFindService.proto.Add.ApiResponse getDefaultInstanceForType() {
        return com.tanmoy.ContactFindService.proto.Add.ApiResponse.getDefaultInstance();
      }

      @java.lang.Override
      public com.tanmoy.ContactFindService.proto.Add.ApiResponse build() {
        com.tanmoy.ContactFindService.proto.Add.ApiResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.tanmoy.ContactFindService.proto.Add.ApiResponse buildPartial() {
        com.tanmoy.ContactFindService.proto.Add.ApiResponse result = new com.tanmoy.ContactFindService.proto.Add.ApiResponse(this);
        result.responseMessage_ = responseMessage_;
        result.responseCode_ = responseCode_;
        if (contactBuilder_ == null) {
          result.contact_ = contact_;
        } else {
          result.contact_ = contactBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.tanmoy.ContactFindService.proto.Add.ApiResponse) {
          return mergeFrom((com.tanmoy.ContactFindService.proto.Add.ApiResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.tanmoy.ContactFindService.proto.Add.ApiResponse other) {
        if (other == com.tanmoy.ContactFindService.proto.Add.ApiResponse.getDefaultInstance()) return this;
        if (!other.getResponseMessage().isEmpty()) {
          responseMessage_ = other.responseMessage_;
          onChanged();
        }
        if (other.getResponseCode() != 0) {
          setResponseCode(other.getResponseCode());
        }
        if (other.hasContact()) {
          mergeContact(other.getContact());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.tanmoy.ContactFindService.proto.Add.ApiResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.tanmoy.ContactFindService.proto.Add.ApiResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object responseMessage_ = "";
      /**
       * <code>string responseMessage = 1;</code>
       */
      public java.lang.String getResponseMessage() {
        java.lang.Object ref = responseMessage_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          responseMessage_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string responseMessage = 1;</code>
       */
      public com.google.protobuf.ByteString
          getResponseMessageBytes() {
        java.lang.Object ref = responseMessage_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          responseMessage_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string responseMessage = 1;</code>
       */
      public Builder setResponseMessage(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        responseMessage_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string responseMessage = 1;</code>
       */
      public Builder clearResponseMessage() {
        
        responseMessage_ = getDefaultInstance().getResponseMessage();
        onChanged();
        return this;
      }
      /**
       * <code>string responseMessage = 1;</code>
       */
      public Builder setResponseMessageBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        responseMessage_ = value;
        onChanged();
        return this;
      }

      private int responseCode_ ;
      /**
       * <code>int32 responseCode = 2;</code>
       */
      public int getResponseCode() {
        return responseCode_;
      }
      /**
       * <code>int32 responseCode = 2;</code>
       */
      public Builder setResponseCode(int value) {
        
        responseCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 responseCode = 2;</code>
       */
      public Builder clearResponseCode() {
        
        responseCode_ = 0;
        onChanged();
        return this;
      }

      private com.tanmoy.ContactFindService.proto.ContactOuterClass.Contact contact_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.tanmoy.ContactFindService.proto.ContactOuterClass.Contact, com.tanmoy.ContactFindService.proto.ContactOuterClass.Contact.Builder, com.tanmoy.ContactFindService.proto.ContactOuterClass.ContactOrBuilder> contactBuilder_;
      /**
       * <code>.Contact contact = 3;</code>
       */
      public boolean hasContact() {
        return contactBuilder_ != null || contact_ != null;
      }
      /**
       * <code>.Contact contact = 3;</code>
       */
      public com.tanmoy.ContactFindService.proto.ContactOuterClass.Contact getContact() {
        if (contactBuilder_ == null) {
          return contact_ == null ? com.tanmoy.ContactFindService.proto.ContactOuterClass.Contact.getDefaultInstance() : contact_;
        } else {
          return contactBuilder_.getMessage();
        }
      }
      /**
       * <code>.Contact contact = 3;</code>
       */
      public Builder setContact(com.tanmoy.ContactFindService.proto.ContactOuterClass.Contact value) {
        if (contactBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          contact_ = value;
          onChanged();
        } else {
          contactBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.Contact contact = 3;</code>
       */
      public Builder setContact(
          com.tanmoy.ContactFindService.proto.ContactOuterClass.Contact.Builder builderForValue) {
        if (contactBuilder_ == null) {
          contact_ = builderForValue.build();
          onChanged();
        } else {
          contactBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.Contact contact = 3;</code>
       */
      public Builder mergeContact(com.tanmoy.ContactFindService.proto.ContactOuterClass.Contact value) {
        if (contactBuilder_ == null) {
          if (contact_ != null) {
            contact_ =
              com.tanmoy.ContactFindService.proto.ContactOuterClass.Contact.newBuilder(contact_).mergeFrom(value).buildPartial();
          } else {
            contact_ = value;
          }
          onChanged();
        } else {
          contactBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.Contact contact = 3;</code>
       */
      public Builder clearContact() {
        if (contactBuilder_ == null) {
          contact_ = null;
          onChanged();
        } else {
          contact_ = null;
          contactBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.Contact contact = 3;</code>
       */
      public com.tanmoy.ContactFindService.proto.ContactOuterClass.Contact.Builder getContactBuilder() {
        
        onChanged();
        return getContactFieldBuilder().getBuilder();
      }
      /**
       * <code>.Contact contact = 3;</code>
       */
      public com.tanmoy.ContactFindService.proto.ContactOuterClass.ContactOrBuilder getContactOrBuilder() {
        if (contactBuilder_ != null) {
          return contactBuilder_.getMessageOrBuilder();
        } else {
          return contact_ == null ?
              com.tanmoy.ContactFindService.proto.ContactOuterClass.Contact.getDefaultInstance() : contact_;
        }
      }
      /**
       * <code>.Contact contact = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.tanmoy.ContactFindService.proto.ContactOuterClass.Contact, com.tanmoy.ContactFindService.proto.ContactOuterClass.Contact.Builder, com.tanmoy.ContactFindService.proto.ContactOuterClass.ContactOrBuilder> 
          getContactFieldBuilder() {
        if (contactBuilder_ == null) {
          contactBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.tanmoy.ContactFindService.proto.ContactOuterClass.Contact, com.tanmoy.ContactFindService.proto.ContactOuterClass.Contact.Builder, com.tanmoy.ContactFindService.proto.ContactOuterClass.ContactOrBuilder>(
                  getContact(),
                  getParentForChildren(),
                  isClean());
          contact_ = null;
        }
        return contactBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:ApiResponse)
    }

    // @@protoc_insertion_point(class_scope:ApiResponse)
    private static final com.tanmoy.ContactFindService.proto.Add.ApiResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.tanmoy.ContactFindService.proto.Add.ApiResponse();
    }

    public static com.tanmoy.ContactFindService.proto.Add.ApiResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ApiResponse>
        PARSER = new com.google.protobuf.AbstractParser<ApiResponse>() {
      @java.lang.Override
      public ApiResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ApiResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ApiResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ApiResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.tanmoy.ContactFindService.proto.Add.ApiResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_FindRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_FindRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ApiResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ApiResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\tadd.proto\032\rcontact.proto\"\031\n\013FindReques" +
      "t\022\n\n\002id\030\001 \001(\005\"W\n\013ApiResponse\022\027\n\017response" +
      "Message\030\001 \001(\t\022\024\n\014responseCode\030\002 \001(\005\022\031\n\007c" +
      "ontact\030\003 \001(\0132\010.Contact2+\n\003add\022$\n\naddCont" +
      "act\022\010.Contact\032\014.ApiResponseB%\n#com.tanmo" +
      "y.ContactFindService.protob\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.tanmoy.ContactFindService.proto.ContactOuterClass.getDescriptor(),
        }, assigner);
    internal_static_FindRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_FindRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_FindRequest_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_ApiResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_ApiResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ApiResponse_descriptor,
        new java.lang.String[] { "ResponseMessage", "ResponseCode", "Contact", });
    com.tanmoy.ContactFindService.proto.ContactOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
